<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-QTN1F52" ignored="0" name="Exception Test" tests="1" failures="1" timestamp="01 Oct 2020 12:57:58 GMT" time="0.06" errors="0">
  <testcase name="customException" time="0.013" classname="ExceptionTest.Execption">
    <failure type="org.testng.TestException" message="
The exception was thrown with the wrong message: expected &amp;quot;This is Error&amp;quot; but got &amp;quot;Error&amp;quot;">
      <![CDATA[org.testng.TestException: 
The exception was thrown with the wrong message: expected "This is Error" but got "Error"
Caused by: java.io.IOException: Error
at ExceptionTest.Execption.customException(Execption.java:28)
... 19 more
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- customException -->
</testsuite> <!-- Exception Test -->
